/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7c23676e-ab8a-4f30-89fb-bf47fbe6749b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JmXIZo6ye",
    "aws_user_pools_web_client_id": "4k4l9nsgfr8kbh8l2n5jel8nji",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://moyhuzwdwfhcdjom4ju4k5ddyu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
